spring.application.name=demo

## H2 DB Config
#spring.datasource.url=jdbc:h2:mem:tododb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=prakash123
#spring.datasource.password=prakash123
#spring.h2.console.enabled=true

## JPA / Hibernate Config
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update


## Postgres Config
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=postgres
spring.datasource.password=191103
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA / Hibernate Config
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=prakash
spring.security.user.password=1234